### PR TITLE
Importing some JavaScript files from "youtube.com"

### PR DESCRIPTION
**Pull request by test123qsaxscdvfg**
There change is very big, all the files that were added were from "youtube.com"

### CODE REVIEW

**Comment by thatjohanntrent-2-googlegroups-com** [comment]
### I'm subscribing to this conversation
Give me access so I can make sort of changes.

**Comment by test123qsaxscdvfg** [comment]
> ### I'm subscribing to this conversation
> Give me access so I can make sort of changes.

ok thanks

**Comment by thatjohanntrent-2-googlegroups-com** [comment]
I'm done helping. thank you for allowing me to make some changes.

**Review by thatjohanntrent-2-googlegroups-com — APPROVED** [review]
These changes so far are very good

**Comment by test123qsaxscdvfg** [comment]
All changes have been secure and completed

**Comment by thatjohanntrent-2-googlegroups-com** [comment]
> All changes have been secure and completed

OK thanks now i will merge it now

**Pull request merged**
